const express = require('express')
const router = express.Router()
const controller = require('../controllers/articlesController.js')

router.get("/", controller.getallarticles)
router.post("/", controller.createarticle)
router.put("/", controller.updatearticle)
router.get("/title", controller.getbytitle)
router.get("/author", controller.getbyauthor)
router.get("/keywords", controller.getbykeywords)
router.get("/areas", controller.getbyareas)
router.get("/year", controller.getbyyear)
router.patch("/title", controller.updatetitle)
router.patch("/author", controller.updateauthor)
router.patch("/resumen", controller.updateresumen)
router.patch("/results", controller.updateresults)
router.patch("/keywords", controller.updatekeywords)
router.patch("/areas", controller.updateareas)
router.patch("/:id/read", controller.updatereadstatus)
router.delete("/:id", controller.deletearticle)

module.exports = router;