const express = require('express')
const router = express.Router()
const controller = require('../controllers/translateController.js')

router.get("/", controller.getAllArticles)
router.post("/", controller.createArticle)
router.get("/title", controller.getArticlesByTitle)
router.get("/author", controller.getArticlesByAuthor)
router.get("/keywords", controller.getArticlesByKeywords)
router.get("/areas", controller.getArticlesByAreas)
router.get("/year", controller.getArticlesByYear)
router.put("/", controller.updateArticle)
router.patch("/title", controller.updateArticleTitle)
router.patch("/author", controller.updateArticleAuthor)
router.patch("/resumen", controller.updateArticleResumen)
router.patch("/results", controller.updateArticleResults)
router.patch("/keywords", controller.updateArticleKeywords)
router.patch("/areas", controller.updateArticleAreas)
router.patch("/:id/read", controller.updateReadStatus)
router.delete("/:id", controller.deleteArticle)

module.exports = router;